name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set Git user info
        run: |
          git config --global user.email "e1000farm@gamil.com"
          git config --global user.name "e1000farm"

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: deploy
        run: yarn deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
